[package]
name = "inception"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.0"
harfbuzz-wasm = { path="../harfbuzz-wasm", features=["kurbo"]}
kurbo = "0.9.0"
ab_glyph_rasterizer = "0.1.8"
